scrfd:
    onnx_file:     "../scrfd_10g_bnkps_shape640x640.onnx"
    engine_file:   "../scrfd_10g_bnkps_shape640x640.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   640
    IMAGE_HEIGHT:  640
    obj_threshold: 0.5
    nms_threshold: 0.45
    mean:          127.5
    std:           128
    detect_mask:   False
    mask_thresh:   0.5
    landmark_std:  1
    feature_steps: [8, 16, 32]
    anchor_sizes:  [[8, 16], [32, 64], [128, 256]]
